Repository Unstructured-IO/unstructured-ingest, pull requests merged in 2024-11, with the labels that each got.

#190 feat/onedrive-destination
  .github/workflows/e2e.yml
  .gitignore
  CHANGELOG.md
  test/integration/connectors/test_onedrive.py
  unstructured_ingest/__version__.py
  unstructured_ingest/v2/processes/connectors/__init__.py
  unstructured_ingest/v2/processes/connectors/onedrive.py
Labels: ready for review

#161 feat/Kafka V2 Connector Source
  CHANGELOG.md
  test/integration/connectors/env_setup/kafka/docker-compose.yaml
  test/integration/connectors/expected_results/kafka/directory_structure.json
  test/integration/connectors/expected_results/kafka/downloads/fake-topic_0_0.txt
  test/integration/connectors/expected_results/kafka/downloads/fake-topic_0_1.txt
  test/integration/connectors/expected_results/kafka/downloads/fake-topic_0_2.txt
  test/integration/connectors/expected_results/kafka/downloads/fake-topic_0_3.txt
  test/integration/connectors/expected_results/kafka/downloads/fake-topic_0_4.txt
  test/integration/connectors/expected_results/kafka/file_data/fake-topic_0_0.json
  test/integration/connectors/expected_results/kafka/file_data/fake-topic_0_1.json
  test/integration/connectors/expected_results/kafka/file_data/fake-topic_0_2.json
  test/integration/connectors/expected_results/kafka/file_data/fake-topic_0_3.json
  test/integration/connectors/expected_results/kafka/file_data/fake-topic_0_4.json
  test/integration/connectors/test_kafka.py
  test/integration/connectors/utils/validation.py
  test_e2e/env_setup/kafka/docker-compose.yml
  test_e2e/env_setup/kafka/kafka-test-helpers/create-kafka-instance.sh
  test_e2e/expected-structured-output/kafka/fake-topic.json
  test_e2e/src/kafka-local.sh
  test_e2e/test-src.sh
  unstructured_ingest/__version__.py
  unstructured_ingest/connector/kafka.py
  unstructured_ingest/v2/processes/connectors/__init__.py
  unstructured_ingest/v2/processes/connectors/kafka/__init__.py
  unstructured_ingest/v2/processes/connectors/kafka/cloud.py
  unstructured_ingest/v2/processes/connectors/kafka/kafka.py
  unstructured_ingest/v2/processes/connectors/kafka/local.py
Labels: v2 migration, ready for review

#231 fix/delta table check region in precheck
  CHANGELOG.md
  requirements/connectors/delta-table.in
  requirements/connectors/delta-table.txt
  unstructured_ingest/__version__.py
  unstructured_ingest/v2/processes/connectors/delta_table.py
Labels: ready for review

#227 fix: Respect Pinecone's metadata size limit
  .github/workflows/e2e.yml
  CHANGELOG.md
  test/integration/connectors/test_pinecone.py
  unstructured_ingest/__version__.py
  unstructured_ingest/v2/processes/connectors/pinecone.py
Labels: bug, ready for review

#201 feat: LanceDB destination
  .github/workflows/e2e.yml
  CHANGELOG.md
  requirements/connectors/lancedb.in
  requirements/connectors/lancedb.txt
  requirements/test.in
  requirements/test.txt
  test/integration/connectors/test_lancedb.py
  unstructured_ingest/v2/processes/connectors/__init__.py
  unstructured_ingest/v2/processes/connectors/lancedb/__init__.py
  unstructured_ingest/v2/processes/connectors/lancedb/aws.py
  unstructured_ingest/v2/processes/connectors/lancedb/azure.py
  unstructured_ingest/v2/processes/connectors/lancedb/gcp.py
  unstructured_ingest/v2/processes/connectors/lancedb/lancedb.py
  unstructured_ingest/v2/processes/connectors/lancedb/local.py
Labels: ready for review

#253 feat: Change LanceDB upload mode to upsert
  CHANGELOG.md
  test/integration/connectors/test_lancedb.py
  unstructured_ingest/__version__.py
  unstructured_ingest/v2/processes/connectors/lancedb/lancedb.py
Labels: ready for review
