Repository Unstructured-IO/unstructured-ingest, pull requests merged in 2024-10, with the labels that each got.

#154 [DS 111] MongoDB v2 source
  .gitignore
  CHANGELOG.md
  test_e2e/check-diff-expected-output.py
  test_e2e/expected-structured-output/mongodb/659daefa21dd8c9054b084b6.json
  test_e2e/expected-structured-output/mongodb/659daefa21dd8c9054b084b7.json
  test_e2e/expected-structured-output/mongodb/659daefa21dd8c9054b084b8.json
  test_e2e/expected-structured-output/mongodb/659daefa21dd8c9054b084b9.json
  unstructured_ingest/__version__.py
  unstructured_ingest/v2/processes/connectors/__init__.py
  unstructured_ingest/v2/processes/connectors/mongodb.py
Labels: v2 migration

#180 Feat: V2 Slack Source Connector
  CHANGELOG.md
  requirements/connectors/slack.in
  requirements/connectors/slack.txt
  test_e2e/expected-structured-output/slack/C07ABKJ83C6.json
  test_e2e/expected-structured-output/slack/cce82000be81b105.xml.json
  test_e2e/test-src.sh
  unstructured_ingest/__version__.py
  unstructured_ingest/v2/cli/utils/click.py
  unstructured_ingest/v2/cli/utils/model_conversion.py
  unstructured_ingest/v2/processes/connectors/__init__.py
  unstructured_ingest/v2/processes/connectors/slack.py
Labels: v2 migration, ready for review

#163 feat/add Delta Tables Destination Connector v2
  CHANGELOG.md
  test/integration/connectors/conftest.py
  test/integration/connectors/test_delta_table.py
  test_e2e/dest/delta-table.sh
  test_e2e/python/test-ingest-delta-table-output.py
  test_e2e/test-dest.sh
  unstructured_ingest/__version__.py
  unstructured_ingest/v2/examples/delta_table.py
  unstructured_ingest/v2/processes/connectors/__init__.py
  unstructured_ingest/v2/processes/connectors/delta_table.py
Labels: v2 migration, ready for review

#143 feat/astradb source connector
  CHANGELOG.md
  test_e2e/check-diff-expected-output.py
  test_e2e/expected-structured-output/astradb/25b75f1d-a2ea-4c97-b75f-1da2eadc97f7.csv.json
  test_e2e/expected-structured-output/astradb/60297eea-73d7-4fca-a97e-ea73d7cfca62.csv.json
  test_e2e/expected-structured-output/astradb/641d99e3-9941-4c18-9d99-e399414c183d.csv.json
  test_e2e/expected-structured-output/astradb/762c0093-2277-4f3e-ac00-932277af3e0e.csv.json
  test_e2e/expected-structured-output/astradb/ae40df94-0b3a-4f89-80df-940b3a6f8966.csv.json
  test_e2e/expected-structured-output/astradb/ingest_test_src/25b75f1d-a2ea-4c97-b75f-1da2eadc97f7.json
  test_e2e/expected-structured-output/astradb/ingest_test_src/60297eea-73d7-4fca-a97e-ea73d7cfca62.json
  test_e2e/expected-structured-output/astradb/ingest_test_src/641d99e3-9941-4c18-9d99-e399414c183d.json
  test_e2e/expected-structured-output/astradb/ingest_test_src/762c0093-2277-4f3e-ac00-932277af3e0e.json
  test_e2e/expected-structured-output/astradb/ingest_test_src/ae40df94-0b3a-4f89-80df-940b3a6f8966.json
  test_e2e/src/astradb.sh
  unstructured_ingest/__version__.py
  unstructured_ingest/v2/processes/connectors/__init__.py
  unstructured_ingest/v2/processes/connectors/astradb.py
Labels: needs edits

#168 feat/Migration - GitLab Source to Connector V2 Structure (#DS-91)
  CHANGELOG.md
  requirements/connectors/gitlab.txt
  test_e2e/expected-structured-output/gitlab/docs/_index.md.json
  test_e2e/src/gitlab.sh
  unstructured_ingest/__version__.py
  unstructured_ingest/v2/processes/connectors/__init__.py
  unstructured_ingest/v2/processes/connectors/gitlab.py
Labels: v2 migration, ready for review
